### PR TITLE
Added support for `integration.response.body.*` in the ResponseParame…

### PR DESCRIPTION
**Pull request by cplee**
…ters as per:

https://forums.aws.amazon.com/message.jspa?messageID=691822#691822

### CODE REVIEW

**Comment by cplee** [comment]
@andrew-templeton are you able to consider this?

**Comment by andrew-templeton** [comment]
Thanks for the reminder. I miss notifications because I maintain many repos.

**Comment by cplee** [comment]
@andrew-templeton No worries, these custom resources are great, thanks for maintaining them.

Will this change be pushed to NPM repo?

**Comment by andrew-templeton** [comment]
Pushed under `0.2.2` to NPM

**Pull request merged**
